/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OceJNIConnector_IGraphRequest */

#ifndef _Included_OceJNIConnector_IGraphRequest
#define _Included_OceJNIConnector_IGraphRequest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
