/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OceJNIConnector */

#ifndef _Included_OceJNIConnector
#define _Included_OceJNIConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OceJNIConnector
 * Method:    graphSize
 * Signature: ([LNode;[LEdge;)I
 */
JNIEXPORT jint JNICALL Java_OceJNIConnector_graphSize
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
